yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
"""yatube URL Configuration.
   The page addresses processed by the posts application's View functions."""
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path(
        'group/',
        views.all_groups,
        name='all_groups'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_posts'),
    path('group/<slug:slug>/follow/',
         views.group_follow,
         name='group_follow'),
    path('group/<slug:slug>/unfollow/',
         views.group_unfollow,
         name='group_unfollow'),
    path('new/',
         views.new_post,
         name='new_post'),
    path('new_group/',
         views.new_group,
         name='new_group'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('<str:username>/',
         views.profile,
         name='profile'),
    path('<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('<str:username>/<int:post_id>/',
         views.post_view,
         name='post'),
    path('<str:username>/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('<str:username>/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
]

yatube/yatube/urls.py
"""Yatube URL Configuration. The `urlpatterns` list routes URLs to views."""
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    #  регистрация и авторизация
    path("auth/", include("users.urls")),

    #  если нужного шаблона для /auth не нашлось в файле users.urls —
    #  ищем совпадения в файле django.contrib.auth.urls
    path("auth/", include("django.contrib.auth.urls")),

    #  раздел администратора
    path("admin/", admin.site.urls),

    # информационный раздел
    path('about/', include('about.urls', namespace='about')),

    #  обработчик для главной страницы ищем в urls.py приложения posts
    path("", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

yatube/templates/includes/comments.html
<!-- Комментарии -->
{% for item in post.comments.all %}
    {% if not post_url %}
      <div class="media col-6 card mb-4">
    {% else %}
      <div class="media card mb-4">
    {% endif %}
        <div class="media-body card-body">
          <h5 class="mt-0">
            <a
              href="{% url 'posts:profile' item.author.username %}"
              name="comment_{{ item.id }}"
            >{{ item.author.username }}</a>
          </h5>
          <p>{{ item.text|linebreaksbr }}</p>
        </div>
      </div>
{% endfor %}

<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated and post_url%}
  <div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' post.author.username post.id %}">
      {% csrf_token %}
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <div class="form-group">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </div>
    </form>
  </div>
{% endif %}

yatube/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">О используемых технологиях</a>
  </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:#8d30ff">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer>

yatube/templates/includes/group_card.html
<div class="mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">
            <!-- Имя автора -->
            {{ group.title }}
          </div>
          <div class="h3 text-muted">
            <!-- username автора -->
               <a
                  class="h5 text-muted"
                  href="{% url 'posts:group_posts' group.slug %}" role="button">
                  #{{ group.slug }}
               </a>
          </div>
          <p class="card-text">
            {{ group.description|linebreaksbr }}
          </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: {{ group.group_following.count }} <br>
              Записей: {{ group.group_posts.count }}
            </div>
          </li>
        <!-- Реализация подписки -->
          {% if not dont_show_button %}
              <li class="list-group-item">
                {% if following %}
                    <a
                      class="btn btn-lg btn-light"
                      href="{% url 'posts:group_unfollow' group.slug %}" role="button">
                      Отписаться
                    </a>
                {% else %}
                    <a
                      class="btn btn-lg btn-primary"
                      href="{% url 'posts:group_follow' group.slug %}" role="button">
                      Подписаться
                    </a>
                {% endif %}
          </li>
          {% endif %}
        </ul>
      </div>
    </div>

yatube/templates/includes/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/includes/nav.html
<nav class="navbar navbar-dark" role="navigation" style="background-color: #343a40;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:#b695e8">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            {% if user.is_superuser %}
                 <a class="p-2 text-light" href="/admin/" >Админ зона</a>
            {% endif %}
                <a class="p-2 text-light" href="{% url 'posts:all_groups' %}">Все сообщества сайта</a>
            <a class="p-2 text-light" href="{% url 'posts:new_post' %}">Новая запись</a>
            <a class="p-2 text-light" href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
            <a class="p-2 text-light" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-light" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-light" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-light" href="{% url 'signup' %}">Регистрация</a>

        {% endif %}
    </nav>
</nav>

yatube/templates/includes/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %} 

yatube/templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author.username }}</strong>
      </a>
      {{ post.text|safe|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group and not ignore_group %}
      <a class="card-link muted" href="{% url 'posts:group_posts' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}

    <p>
      <div>
        {% if post.comments.exists %}
          <div>
            <a
              class="h5 text-muted"
              href="{% url 'posts:post' post.author.username post.id %}" role="button">
              Комментариев: {{ post.comments.count }}
            </a>
          </div>
        {% endif %}
      </div>
    </p>

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if user.is_authenticated and not post_url %}
            <a class="btn btn- btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
                Добавить комментарий
            </a>
        {% endif %}

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
          <a class="btn btn-sm btn-info"
             href="{% url 'posts:post_edit' post.author.username post.id %}"
             role="button">
            Редактировать
          </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
      {% include 'includes/comments.html' with post=post post_url=post_url%}
</div>

yatube/templates/includes/profile_card.html
<div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">
            <!-- Имя автора -->
            {{ author.get_full_name }}
          </div>
          <div class="h3 text-muted">
            <!-- username автора -->
               <a
                  class="h3 text-muted"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                  @{{ author.username }}
                </a>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: {{ author.following.count }} <br>
              Подписан: {{ author.follower.count }}
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
              <!-- Количество записей -->
              Записей: {{ author.posts.count }}
            </div>
          </li>
        <!-- Реализация подписки -->
          {% if user.username != author.username %}
              <li class="list-group-item">
                {% if following %}
                    <a
                      class="btn btn-lg btn-light"
                      href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                      Отписаться
                    </a>
                {% else %}
                    <a
                      class="btn btn-lg btn-primary"
                      href="{% url 'posts:profile_follow' author.username %}" role="button">
                      Подписаться
                    </a>
                {% endif %}
              </li>
          {% endif %}
        </ul>
      </div>
    </div>