yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
"""yatube URL Configuration.
   The page addresses processed by the posts application's View functions."""
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path(
        'group/',
        views.all_groups,
        name='all_groups'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_posts'),
    path('group/<slug:slug>/follow/',
         views.group_follow,
         name='group_follow'),
    path('group/<slug:slug>/unfollow/',
         views.group_unfollow,
         name='group_unfollow'),
    path('new/',
         views.new_post,
         name='new_post'),
    path('new_group/',
         views.new_group,
         name='new_group'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('<str:username>/',
         views.profile,
         name='profile'),
    path('<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('<str:username>/<int:post_id>/',
         views.post_view,
         name='post'),
    path('<str:username>/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('<str:username>/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
]

yatube/yatube/urls.py
"""Yatube URL Configuration. The `urlpatterns` list routes URLs to views."""
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    #  регистрация и авторизация
    path("auth/", include("users.urls")),

    #  если нужного шаблона для /auth не нашлось в файле users.urls —
    #  ищем совпадения в файле django.contrib.auth.urls
    path("auth/", include("django.contrib.auth.urls")),

    #  раздел администратора
    path("admin/", admin.site.urls),

    # информационный раздел
    path('about/', include('about.urls', namespace='about')),

    #  обработчик для главной страницы ищем в urls.py приложения posts
    path("", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

yatube/posts/models.py
"""Database interaction models."""
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """
    Stores one group where users can submit their posts.
    No strict relate.
    """

    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True,
                            verbose_name='Уникальный идентификатор группы')
    description = models.TextField(blank=True, null=True,
                                   verbose_name='Описание')

    class Meta:
        ordering = ['title']
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        """
        Overriding base __str__. Outputs the name of the group.
        """
        return self.title


class Post(models.Model):
    """
    Stores one user or admin post.
    Related to: model: `group.Group` and: model:` auth.User`.
    """

    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='group_posts',
                              verbose_name='Группа')
    text = RichTextField(verbose_name='Текст поста', blank=False)
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата создания')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts', verbose_name='Автор')
    image = models.ImageField(upload_to='posts/', blank=True, null=True,
                              verbose_name='Изображение')

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        """
        Overriding base __str__.
        """
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='К посту:')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор комментария')
    text = models.TextField(verbose_name='Комментарий', blank=False)
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата создания')

    class Meta:
        ordering = ['created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class FollowAuthor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower',
                             verbose_name='Подписчик')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following',
                               verbose_name='Блогер')

    class Meta:
        verbose_name = 'Подписка на автора'
        verbose_name_plural = 'Подписки на авторов'


class FollowGroup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='group_follower',
                             verbose_name='Подписчик')
    group = models.ForeignKey(Group, on_delete=models.CASCADE,
                              related_name='group_following',
                              verbose_name='Группа')

    class Meta:
        verbose_name = 'Подписка на группу'
        verbose_name_plural = 'Подписки на группы'

yatube/posts/forms.py
from autoslug.settings import slugify
from django import forms

from .models import Comment, Post, Group


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {
            'text': 'Текст тут',
            'group': 'Группа',
            'image': 'Изображение'
        }
        help_texts = {
            'text': 'Вы можете рассказать нам о своем дне, '
                    'или о том какая у вас замечательная собака',
            'group': 'Выберете группу для публикации, если хотите :^)',
            'image': 'Хотите ли вы проиллюстрировать свой пост?'
        }


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['title', 'slug', 'description']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
"""View-functions for describing the inner workings of the site pages."""
from autoslug.settings import slugify
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET

from .forms import CommentForm, PostForm, GroupForm
from .models import FollowAuthor, Group, Post, User, FollowGroup


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)


@require_GET
def index(request):
    post_list = cache.get('index_page')
    if post_list is None:
        post_list = Post.objects.all()
        cache.set('index_page', post_list, timeout=20)
    paginator = Paginator(post_list, settings.PAGINATOR_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/index.html', {'page': page})


def all_groups(request):
    groups = Group.objects.all()
    paginator = Paginator(groups, settings.PAGINATOR_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/groups.html', {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = group.group_posts.all()
    paginator = Paginator(posts_list, settings.PAGINATOR_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/group.html', {'group': group, 'page': page})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_list = author.posts.all()
    paginator = Paginator(posts_list, settings.PAGINATOR_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    following = (
            request.user.is_authenticated
            and author != request.user
            and FollowAuthor.objects.filter(
            user=request.user,
            author=author
        ).exists()
    )
    return render(request, 'posts/profile.html', {
        'author': author,
        'page': page,
        'following': following
    })


def post_view(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, id=post_id)
    form = CommentForm(request.POST or None)
    following = (
            request.user.is_authenticated
            and post.author != request.user
            and FollowAuthor.objects.filter(
            user=request.user,
            author=post.author
        ).exists()
    )
    return render(request, 'posts/post.html', {
        'author': post.author,
        'post': post,
        'form': form,
        'following': following
    })


@login_required
def post_edit(request, username, post_id):
    if request.user.username != username:
        return redirect('posts:post', username=username, post_id=post_id)
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post', username=username, post_id=post_id)
    return render(request, 'posts/new_post.html', {
        'post': post,
        'form': form,
        'edit': True
    })


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_form = form.save(commit=False)
        new_form.author = request.user
        new_form.save()
        return redirect('posts:index')
    return render(request, 'posts/new_post.html', {
        'form': form,
        'edit': False
    })


@login_required
def new_group(request):
    form = GroupForm(request.POST or None)
    if form.is_valid():
        new_form = form.save(commit=False)
        new_form.save()
        return redirect('posts:group_posts', slug=new_form.slug)
    return render(request, 'posts/new_group.html', {'form': form})


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return redirect('posts:post', username=username,
                    post_id=post_id)


@require_GET
@login_required
def follow_index(request):
    follow_author_list = Post.objects.filter(
        author__following__user=request.user
    )
    follow_group_list = Post.objects.filter(
        group__group_following__user=request.user
    )
    follow_post_list = follow_author_list | follow_group_list
    paginator = Paginator(follow_post_list, settings.PAGINATOR_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'posts/follow.html', {'page': page})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user and not FollowAuthor.objects.filter(
        author=author,
        user=user
    ).exists():
        FollowAuthor.objects.create(
            user=user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        FollowAuthor,
        author__username=username,
        user=request.user
    ).delete()
    return redirect('posts:profile', username=username)


@login_required
def group_follow(request, slug):
    group = get_object_or_404(Group, slug=slug)
    user = request.user
    if not FollowGroup.objects.filter(
        user=user,
        group=group
    ).exists():
        FollowGroup.objects.create(
            user=user,
            group=group
        )
    return redirect('posts:group_posts', slug=slug)


@login_required
def group_unfollow(request, slug):
    get_object_or_404(
        FollowGroup,
        group__slug=slug,
        user=request.user
    ).delete()
    return redirect('posts:group_posts', slug=slug)

yatube/templates/posts/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'includes/nav.html' %}
    <main>
        <div class="container">
            <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
     {% include 'includes/footer.html' %}
</body>

</html>

yatube/templates/posts/follow.html
{% extends "posts/base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

  <div class="container">

    {% include "includes/menu.html" with follow=True index=False %}


    {% for post in page %}
      {% include "includes/post_item.html" with post=post %}
    {% endfor %}

    {% include "includes/paginator.html" with items=page %}
  </div>



{% endblock %}

yatube/templates/posts/group.html
{% extends "posts/base.html" %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block header %}{% endblock %}

{% block content %}
    {% include "includes/group_card.html" %}
    {% for post in page %}
        {% include "includes/post_item.html" with post=post ignore_group=True without_comment_button=False %}
    {%  endfor %}

    {% include "includes/paginator.html" %}

{% endblock %}

yatube/templates/posts/groups.html
{% extends "posts/base.html" %}
{% block title %}Сообщества сайта{% endblock %}
{% block header %}Сообщества сайта:{% endblock %}
{% block content %}
    <a class="p-2 h3 text-dark" href="{% url 'posts:new_group' %}">Создать группу</a><br><br>
    {% for group in page %}
        {% include "includes/group_card.html" with dont_show_button=True %}
    {%  endfor %}

{% endblock %}

yatube/templates/posts/index.html
{% extends "posts/base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

  <div class="container">

    {% include "includes/menu.html" with index=True %}


    {% for post in page %}
      {% include "includes/post_item.html" with post=post %}
    {% endfor %}

    {% include "includes/paginator.html" with items=page %}
  </div>



{% endblock %}

yatube/templates/posts/new_group.html
{% extends "posts/base.html" %}

{% block title %}Создать группу{% endblock %}

{% block header %}Создать группу{% endblock %}

{% block content %}
    {% load user_filters %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Создать группу </div>
                <div class="card-body">

                {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                    <form method="post" enctype="multipart/form-data" action={% url 'posts:new_group' %}>
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }} {% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">Создать</button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->

{% endblock %}

yatube/templates/posts/new_post.html
{% extends "posts/base.html" %}

{% block title %}
    {% if post %}
        Редактировать запись
    {% else %}
        Добавить запись
    {% endif %}
{% endblock %}

{% block header %}
    {% if post %}
        Редактировать запись
    {% else %}
        Добавить запись
    {% endif %}
{% endblock %}

{% block content %}
    {% load user_filters %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    {% if edit %}
                        Редактировать запись
                    {% else %}
                        Добавить запись
                    {% endif %}
                </div>
                <div class="card-body">

                    <form method="post" enctype="multipart/form-data" action=
                        {% if edit %}
                            {% url 'posts:post_edit' user.username form.instance.id %}
                        {% else %}
                            {% url 'posts:new_post' %}
                        {% endif %}>
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }} {% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {% if post %}
                                        Сохранить
                                    {% else %}
                                        Добавить
                                    {% endif %}
                                </button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->

{% endblock %}

yatube/templates/posts/post.html
{% extends "posts/base.html" %}
{% block title %}Пост пользователя {{ author.username }}{% endblock %}
{% block header %}Пост пользователя {{ author.username }}{% endblock %}
{% block content %}

<main role="main" class="container">
  <div class="row">
    {% include "includes/profile_card.html" %}
    <div class="col-md-9">
    <!-- Пост -->
      {% include "includes/post_item.html" with post=post post_url=True %}
    </div>
  </div>
</main>

{% endblock %}

yatube/templates/posts/profile.html
{% extends "posts/base.html" %}
{% block title %}Профиль пользователя {{ author.username }}{% endblock %}
{% block header %}Профиль пользователя {{ author.username }}{% endblock %}
{% block content %}

<main role="main" class="container">
  <div class="row">
    {% include "includes/profile_card.html" %}

    <div class="col-md-9">

        {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}

        {% include "includes/paginator.html" %}
    </div>
  </div>
</main>

{% endblock %}